### ISSUE TITLE
Idea: replace underscore in project name into dashes

### ISSUE THREAD

**Issue by davidpham87** [OrgPad-com/volcano#1]
Hello,

First of all, thanks a lot for the project. I think it could be interesting in your template if you could convert the underscore into dashes in the clojure namespace.

Best regards,
David

**Comment by pavel-klavik** [comment]
Hi, sorry, I am lost. Can you explain more what you mean?

**Comment by davidpham87** [comment]
Yes, sorry for the imprecision.

Whenever you make a new project with `lein new volcano app_name` the namespace generated by lein will have `app_name` in the namespace name. But it is easy to circumvent the issue, just write `app-name` in Lein.
