### ISSUE TITLE
How to link to a SPA?

### ISSUE THREAD

**Issue by SignSpice** [OrgPad-com/volcano#7]
I've made a simple static site, and I want one of the pages to be a SPA, but it is not clear to me how to go about that.

The only tidbit I could find was this part of the readme:

> `:routes ` - A Bidi data structure describing the routes on your web. Not all routes have to be used by static pages, so you can easily link your static websites to your SPA.

It's quite possible I'm missing something that should be obvious, I'm new to Clojure/(Script) and this is my first project with it.

**Comment by pavel-klavik** [comment]
Thanks for the question. This is not something we discuss in the documentation for Volcano but it is how we use Volcano in OrgPad as well.

Our main server is build using Ring, using the Luminus template: https://luminusweb.com/. There are three types of routes:

- Certain routes correspond to static pages. In OrgPad's case, it is http://orgpad.com and everything with http://orgpad.com/l/ prefix. These routes are served from static HTML generated by Volcano using nginx. But our application server could serve them from resources as well: we could just store them in resources directory which is packaged inside the compiled Uberjar of the server.
- Certain routes serve data or do changes. For instance, we have routes for serving stored files, images, updating user's profile photo, etc.
- Certain routes lead to SPA. For instance, both http://orgpad.com/list and http://orgpad.com/login lead to SPA. These routes serve the same small HTML file called app.html which loads the main JS files. In Clojurescript, on startup, we check the url in the address bar and set up the current route in the application. So the former link displays the list of all documents and the latter link displays the login page. In the future, we might do server side rendering to speed up the process, so some initial data coulx be added to app.html served by the server. While we could in principle use Volcano to generate app.html, we just keep a simple static HTML file in resources and we update some metadata inside it using Selmer to have different metadata for links leading to documents, etc.

So Volcano helps us in the first point. It is perfectly fine if you are lost when starting web development and the entire Clojure ecosystem. It is quite tricky to find these general information how to build SPA, and everything I know I learned along the way of working on OrgPad.

**Comment by SignSpice** [comment]
@pavel-klavik Thank you for the detailed response. That makes it much more clear to me. 

In my case, I have a completely static server side. (I'm hosting it on Netlify). I want to serve a page that is interactive via ClojureScript + some React interop. 

Maybe SPA gives the wrong picture, as it is fully on the client-side, with no server-side with which to interact or decide what gets served. 

Perhaps it would make the most sense to make the interactive page it's own project. Develop it separately, compile it for production, and then include the compiled JS in the volcano based static project.

**Comment by pavel-klavik** [comment]
Yes, that sounds like the correct solution. You cannot build a React app using Volcano. But you can build the HTML file which links to your JS file. And you can develop the app separately using Shadow-cljs or Figwheel for hot code reloading.

Btw. what people normally mean by SPA is that you have links on the webpage, but instead loading a new webpage when user clicks on them, you tell the browser not to do that but you instead update the state of the app, display something else.

**Comment by SignSpice** [comment]
@pavel-klavik Ah okay, Got it. Thank you for the quick response and the clarification.
